# Generated by Django 3.1.4 on 2021-11-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fixed_pricings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=200)),
                ('to_or_from', models.CharField(max_length=200)),
                ('sedan_price', models.FloatField(default=0)),
                ('bus_price', models.FloatField(default=0)),
                ('xxl_bus_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='variable_pricings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_price', models.FloatField(default=0)),
                ('km_price', models.FloatField(default=0)),
                ('minute_price', models.FloatField(default=0)),
                ('from_person', models.IntegerField(default=0)),
                ('to_person', models.IntegerField(default=0)),
                ('vehicle_type', models.CharField(max_length=200)),
                ('disable', models.BooleanField(default=False)),
            ],
        ),
    ]
