# Generated by Django 3.1.4 on 2021-11-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxiairnl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='name',
            new_name='number',
        ),
    ]
