# Generated by Django 3.1.4 on 2021-11-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxiairnl', '0003_auto_20211108_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_details',
            name='flight_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
